spring:
  application:
    name: patient-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/patient_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456789}